steps:
- name: node
  dir: 'google'
  entrypoint: npm
  args: ['install']

- name: node
  dir: 'google'
  entrypoint: npm
  args: ['run', 'build']

- name: 'gcr.io/cloud-builders/gcloud'
  dir: 'google'
  args:
  - functions
  - deploy
  - function-1
  - --source=./build
  - --trigger-topic=exodia-topic
  - --region=australia-southeast1
