name: Me try CD

on:
  push:
    branches: [ master ]

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aws/src

    steps:
    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: checkout repo
      uses: actions/checkout@v2
      
    - name: setup node v 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: clean install
      run: npm ci

    - name: sam/webpack build
      run: npm run build

    - name: sam deploy
      run: npm run deploy
